# SQL Queries Practice

**Objective:** Practice common SQL queries using a sample student database.

**Topics:** `CREATE TABLE`, `INSERT`, `SELECT`, `WHERE`, `ORDER BY`, `DISTINCT`, aggregate functions, `GROUP BY`, `HAVING`, `UPDATE`, `DELETE`, `LIKE`, `BETWEEN`, subqueries, and joins.

These examples use SQLite syntax and can be run in Google Colab. The setup cell creates a temporary database and sample records.

In [1]:
import sqlite3
import pandas as pd

connection = sqlite3.connect(":memory:")
cursor = connection.cursor()

cursor.execute("""
CREATE TABLE students (
    Student_ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Department TEXT,
    Attendance INTEGER,
    Final_Marks INTEGER
)
""")

students = [
    (101, "Kavya", "BCA", 88, 86),
    (102, "Arjun", "BCS", 79, 77),
    (103, "Ishita", "BCA", 94, 93),
    (104, "Manoj", "BCS", 67, 65),
    (105, "Divya", "BCA", 83, 82),
    (106, "Kiran", "BCS", 72, 70),
    (107, "Nisha", "BCS", 96, 95),
    (108, "Varun", "BCA", 74, 73),
    (109, "Meera", "BCS", 86, 85),
    (110, "Sanjay", "BCA", 61, 60)
]
cursor.executemany("INSERT INTO students VALUES (?, ?, ?, ?, ?)", students)
connection.commit()

print("Student table created and sample records inserted.")

Student table created and sample records inserted.

## Query 1: Display all records
Use `SELECT *` to display every column and row.

In [2]:
SELECT_ALL = "SELECT * FROM students ORDER BY Student_ID;"
pd.read_sql_query(SELECT_ALL, connection)

   Student_ID    Name Department  Attendance  Final_Marks
0         101   Kavya        BCA          88           86
1         102   Arjun        BCS          79           77
2         103  Ishita        BCA          94           93
3         104   Manoj        BCS          67           65
4         105   Divya        BCA          83           82
5         106   Kiran        BCS          72           70
6         107   Nisha        BCS          96           95
7         108   Varun        BCA          74           73
8         109   Meera        BCS          86           85
9         110  Sanjay        BCA          61           60

## Query 2: Select specific columns
Display each student's name, department, and final marks.

In [3]:
query = """
SELECT Name, Department, Final_Marks
FROM students
ORDER BY Name;
"""
pd.read_sql_query(query, connection)

     Name Department  Final_Marks
0   Arjun        BCS           77
1   Divya        BCA           82
2  Ishita        BCA           93
3   Kavya        BCA           86
4   Kiran        BCS           70
5   Manoj        BCS           65
6   Meera        BCS           85
7   Nisha        BCS           95
8  Sanjay        BCA           60
9   Varun        BCA           73

## Query 3: Filter with WHERE
Find students whose final marks are greater than 80.

In [4]:
query = """
SELECT Name, Final_Marks
FROM students
WHERE Final_Marks > 80
ORDER BY Final_Marks DESC;
"""
pd.read_sql_query(query, connection)

     Name  Final_Marks
0   Nisha           95
1  Ishita           93
2   Kavya           86
3   Meera           85
4   Divya           82

## Query 4: Sort with ORDER BY
List students from highest to lowest final marks.

In [5]:
query = """
SELECT Name, Final_Marks
FROM students
ORDER BY Final_Marks DESC;
"""
pd.read_sql_query(query, connection)

     Name  Final_Marks
0   Nisha           95
1  Ishita           93
2   Kavya           86
3   Meera           85
4   Divya           82
5   Arjun           77
6   Varun           73
7   Kiran           70
8   Manoj           65
9  Sanjay           60

## Query 5: DISTINCT values
Display each department only once.

In [6]:
query = "SELECT DISTINCT Department FROM students ORDER BY Department;"
pd.read_sql_query(query, connection)

  Department
0        BCA
1        BCS

## Query 6: Aggregate functions
Calculate the number of students, average marks, highest marks, and lowest marks.

In [7]:
query = """
SELECT COUNT(*) AS Student_Count,
       ROUND(AVG(Final_Marks), 2) AS Average_Marks,
       MAX(Final_Marks) AS Highest_Marks,
       MIN(Final_Marks) AS Lowest_Marks
FROM students;
"""
pd.read_sql_query(query, connection)

   Student_Count  Average_Marks  Highest_Marks  Lowest_Marks
0             10           78.6             95            60

## Query 7: GROUP BY
Calculate the average final marks for each department.

In [8]:
query = """
SELECT Department, ROUND(AVG(Final_Marks), 2) AS Average_Marks
FROM students
GROUP BY Department
ORDER BY Department;
"""
pd.read_sql_query(query, connection)

  Department  Average_Marks
0        BCA           78.8
1        BCS           78.4

## Query 8: HAVING
Show departments whose average final marks are above 75.

In [9]:
query = """
SELECT Department, ROUND(AVG(Final_Marks), 2) AS Average_Marks
FROM students
GROUP BY Department
HAVING AVG(Final_Marks) > 75
ORDER BY Department;
"""
pd.read_sql_query(query, connection)

  Department  Average_Marks
0        BCA           78.8
1        BCS           78.4

## Query 9: BETWEEN
Find students whose final marks are between 70 and 85, inclusive.

In [10]:
query = """
SELECT Name, Final_Marks
FROM students
WHERE Final_Marks BETWEEN 70 AND 85
ORDER BY Final_Marks;
"""
pd.read_sql_query(query, connection)

    Name  Final_Marks
0  Kiran           70
1  Varun           73
2  Arjun           77
3  Divya           82
4  Meera           85

## Query 10: LIKE
Find students whose names start with the letter 'M'.

In [11]:
query = """
SELECT Name
FROM students
WHERE Name LIKE 'M%'
ORDER BY Name;
"""
pd.read_sql_query(query, connection)

    Name
0  Manoj
1  Meera

## Query 11: Subquery
Find students who scored above the overall average final marks.

In [12]:
query = """
SELECT Name, Final_Marks
FROM students
WHERE Final_Marks > (SELECT AVG(Final_Marks) FROM students)
ORDER BY Final_Marks DESC;
"""
pd.read_sql_query(query, connection)

     Name  Final_Marks
0   Nisha           95
1  Ishita           93
2   Kavya           86
3   Meera           85
4   Divya           82

## Query 12: INNER JOIN
Create a departments table and show each student with the department head.

In [13]:
cursor.execute("""
CREATE TABLE departments (
    Department TEXT PRIMARY KEY,
    HOD TEXT
)
""")
cursor.executemany(
    "INSERT INTO departments (Department, HOD) VALUES (?, ?)",
    [("BCA", "Dr. Sharma"), ("BCS", "Dr. Mehta")]
)
connection.commit()

query = """
SELECT students.Name, students.Department, departments.HOD
FROM students
INNER JOIN departments
ON students.Department = departments.Department
ORDER BY students.Student_ID;
"""
pd.read_sql_query(query, connection)

     Name Department         HOD
0   Kavya        BCA  Dr. Sharma
1   Arjun        BCS   Dr. Mehta
2  Ishita        BCA  Dr. Sharma
3   Manoj        BCS   Dr. Mehta
4   Divya        BCA  Dr. Sharma
5   Kiran        BCS   Dr. Mehta
6   Nisha        BCS   Dr. Mehta
7   Varun        BCA  Dr. Sharma
8   Meera        BCS   Dr. Mehta
9  Sanjay        BCA  Dr. Sharma

## Query 13: LEFT JOIN
A `LEFT JOIN` keeps all rows from the left table, even if no matching department exists.

In [14]:
query = """
SELECT students.Name, students.Department, departments.HOD
FROM students
LEFT JOIN departments
ON students.Department = departments.Department
ORDER BY students.Student_ID;
"""
pd.read_sql_query(query, connection)

     Name Department         HOD
0   Kavya        BCA  Dr. Sharma
1   Arjun        BCS   Dr. Mehta
2  Ishita        BCA  Dr. Sharma
3   Manoj        BCS   Dr. Mehta
4   Divya        BCA  Dr. Sharma
5   Kiran        BCS   Dr. Mehta
6   Nisha        BCS   Dr. Mehta
7   Varun        BCA  Dr. Sharma
8   Meera        BCS   Dr. Mehta
9  Sanjay        BCA  Dr. Sharma

## Query 14: UPDATE
Update one student's attendance, then display the changed value.

In [15]:
cursor.execute("UPDATE students SET Attendance = 90 WHERE Student_ID = 102")
connection.commit()
pd.read_sql_query("SELECT Student_ID, Name, Attendance FROM students WHERE Student_ID = 102;", connection)

   Student_ID   Name  Attendance
0         102  Arjun          90

## Query 15: DELETE
Delete a temporary sample record and verify it was removed.

In [16]:
cursor.execute("INSERT INTO students VALUES (999, 'Temporary', 'BCA', 50, 50)")
cursor.execute("DELETE FROM students WHERE Student_ID = 999")
connection.commit()
print("Temporary record count:", cursor.execute("SELECT COUNT(*) FROM students WHERE Student_ID = 999").fetchone()[0])

Temporary record count: 0

## Quick revision

- `SELECT` retrieves data.
- `WHERE` filters rows.
- `ORDER BY` sorts results.
- `GROUP BY` groups rows for aggregate calculations.
- `HAVING` filters grouped results.
- `JOIN` combines related tables.
- `UPDATE` modifies rows; `DELETE` removes rows.

**Note:** The notebook focuses only on SQL queries and their results; the earlier Internship Week 1 Python/Pandas practice section has been removed.